steps:
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm install
  lint:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - npm run lint
  test:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm run test:ember
when:
  event: pull_request
