steps:
  install:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm ci
  lint:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm run lint
  test:
    image: danlynn/ember-cli:6.1.0-node_22.12
    commands:
      - npm run test:ember
when:
  event: pull_request
